#!/bin/sh -e

PROGDIR=$(dirname "$(readlink -f "$0")")

# Fix a bug where active window is lost if dmenu pops under cursor
active_window=$(xdotool getactivewindow)
emoji=$(cat "$PROGDIR/emoji.txt" | dmenu -i -l 30 | sed 's/ .*//')
xdotool windowactivate "$active_window"

if [ -z "$emoji" ]; then
    exit
fi

if [ "$1" = copy ]; then
    printf "$emoji" | xclip -selection clipboard
    echo "Copied $emoji to clipboard!"
else
    xdotool type -delay 100 "$emoji"
fi
